// Set up constants for types
const ActionTypes = {
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
  LOGOUT_USER_FAILURE: 'LOGOUT_USER_FAILURE',
  UPDATE_USERNAME: 'UPDATE_USERNAME',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  NO_USER_CHANGE: 'NO_USER_CHANGE',
  UPDATE_SERVER_SUCCESS: 'UPDATE_SERVER_SUCCESS',
  UPDATE_SERVER_FAILURE: 'UPDATE_SERVER_FAILURE',
  SERVER_INFO_RESET: 'SERVER_INFO_RESET'
};

module.exports = ActionTypes;
