/**
 * Login Form presentational component
 *
 * Renders the login form and error and success messages if they exist. Handles
 * the onsubmit event for the form and the onchange event for the username and
 * password fields.
 *
 * @parent /client/src/components/LoginContainer.jsx
 *
 * @export LoginForm
 */

// Import dependencies
import React, { PropTypes } from 'react';

/**
 * Login form function
 *
 * Returns an HTML login form. Renders a success or error message if they exist.
 * Attaches the onSubmit function to the onsubmit event of the form and attaches
 * the onChange function to the onchange event of the username and password fields.
 *
 * @param {Function} $onSubmit - Function that handles user authentication and
 *                                updating of Redux state with user information.
 * @param {Function} $onChange - Function that handles updating of Redux state
 *                                with information entered by user.
 * @param {Object} $errors - Object containing any errors generated by user actions.
 * @param {String} $successMessage - Message created upon successful user actions.
 *
 * @return - HTML elements.
 */
const LoginForm = ({
  onSubmit,
  onChange,
  errors,
  successMessage,
  user
}) => (
  <div className="login row">
    <div className="login-form col-md-6 col-md-offset-3">
      <h4>Login</h4>
      <p>Welcome to the React Redux with Auth App</p>
      <form className="login-form form-horizontal" id="loginForm" onSubmit={onSubmit}>
        {successMessage && <p className="success-message">{successMessage}</p>}
        {errors && errors.summary && <p className="error-message">{errors.summary}</p>}
        <fieldset>
          <div className="col-md-12 form-group">
            <input
              type="text"
              className="form-control"
              id="username"
              placeholder="username"
              name="username"
              autoFocus
              required
              onChange={onChange}
            />
          </div>
          <div className=" col-md-12 form-group">
            <input
              type="password"
              className="form-control"
              id="password"
              placeholder="password"
              name="password"
              required
              onChange={onChange}
            />
          </div>
          <input
            type="submit"
            className="btn btn-login"
            id="login-button"
            value="Sign in"
          />
        </fieldset>
      </form>
    </div>
  </div>
);

/**
 * Defines and validates the props for the component
 *
 * Ensures the type for each prop and that the prop exists if it is required.
 *
 * @see PropTypes
 *
 * @return null
 */
LoginForm.propTypes = {
  onSubmit: PropTypes.func.isRequired,
  onChange: PropTypes.func.isRequired,
  errors: PropTypes.object.isRequired,
  successMessage: PropTypes.string.isRequired,
  user: PropTypes.object.isRequired
};

// Set the default export for the module
export default LoginForm;
